# Generated by Django 5.1.2 on 2024-10-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0003_alter_riskmatrix_impact_alter_riskmatrix_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmatrix',
            name='tr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_matrix', to='tr.tr'),
        ),
    ]
