# Generated by Django 5.1.2 on 2024-10-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0004_alter_riskmatrix_tr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskmatrix',
            name='impact',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='riskmatrix',
            name='probability',
            field=models.PositiveIntegerField(),
        ),
    ]
