# Generated by Django 5.1.2 on 2024-10-24 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0005_alter_riskmatrix_impact_alter_riskmatrix_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tr',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=100),
        ),
    ]
