# Generated by Django 5.1.2 on 2024-10-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tr', '0006_tr_created_at_tr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tr',
            name='concluded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tr',
            name='previous_status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=9),
        ),
        migrations.AddField(
            model_name='tr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tr',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=9),
        ),
    ]
