services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

  ollama:
    build:
      dockerfile: ./ollama/ollama.Dockerfile
    restart: always
    volumes:
      - ollama:/root/.ollama
    networks:
      - ollama

  ollama-api:
    build:
      dockerfile: ./ollama/app.Dockerfile
    ports:
      - 8001:8001
    networks:
      - ollama
      - app
    depends_on:
      - ollama
    develop:
      watch:
        - action: sync+restart
          path: ./ollama/app.py
          target: /app
        - action: rebuild
          path: ./ollama/pyproject.toml

  licitacaorio:
    build:
      dockerfile: ./licitacaorio/Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    networks:
      - app
    volumes:
      - static:/app/assets
    depends_on:
      - db
      - ollama
      - ollama-api
      # - dashboard
    develop:
      watch:
        - action: sync+restart
          path: ./licitacaorio
          target: /app
        - action: rebuild
          path: ./licitacaorio/pyproject.toml

  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 1337:80
    depends_on:
      - licitacaorio
    networks:
      - app
    volumes:
      - static:/app/assets
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf.d

volumes:
  postgres:
  ollama:
  static:

networks:
  app:
    driver: bridge
  ollama:
    driver: bridge
