services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

  ollama:
    build:
      dockerfile: ./ollama/ollama.Dockerfile
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ollama:/ollama
    networks:
      - ollama

  ollama-api:
    build:
      dockerfile: ./ollama/app.Dockerfile
    ports:
      - 8001:8001
    networks:
      - ollama
      - app
    depends_on:
      - ollama

  licitacaorio:
    build:
      dockerfile: ./licitacaorio/Dockerfile
      args:
        SECRET_KEY: ${SECRET_KEY}
    env_file: .env
    networks:
      - app
    volumes:
      - static:/app/assets
    depends_on:
      - db
      - ollama
      - ollama-api
      # - dashboard

  nginx:
    build:
      dockerfile: ./nginx/Dockerfile
    ports:
      - 1337:80
    depends_on:
      - licitacaorio
    networks:
      - app
    volumes:
      - static:/app/assets

volumes:
  postgres:
  ollama:
  static:

networks:
  app:
    driver: bridge
  ollama:
    driver: bridge
