# Generated by Django 5.1.2 on 2024-10-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído')], default='Pendente', max_length=100),
        ),
        migrations.AlterField(
            model_name='admprocess',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='contractestimate',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='installment',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
