# Generated by Django 5.1.2 on 2024-10-17 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etp',
            old_name='reasons',
            new_name='justification',
        ),
    ]
