# Generated by Django 5.1.2 on 2024-10-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0002_rename_reasons_etp_justification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketresearch',
            old_name='requesting_organization',
            new_name='requester',
        ),
    ]
