# Generated by Django 5.1.2 on 2024-10-24 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etp', '0002_etp_status_alter_admprocess_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
